version: "3"
services:
  web:
    image: traefik/whoami
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.http.services.web.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=Host(`app.appxl.ga`)"
networks:
  traefik-net:
    external: true